### ISSUE TITLE
Parse command-line parameters with boost program options

### ISSUE THREAD

**Issue by slizzered** [ComputationalRadiationPhysics/haseongpu#15]
Boost program options ftw!

This will also define a syntax for a possible config file, see #10 

Multiple steps are necessary:
- [x] use CMake (see #27)
- [x] fix the CPLUS_INCLUDE_PATH (see #26)
- [x] fix compiling issues related to the Boost 1.55-fix (see #19)
- [x] think deeply about the structure of the parameters:
  - should there be switches? (like `--use-reflections` to enable reflections)
  - should there be only options with defaults? (like `--use-reflections=1` to enable reflections)
  - what is a good way to specify the runmodes
  - what parameters **must** be given every time?
  - can we use sane defaults for everything else?
- [x] with this new knowledge, implement the behaviour
